// Phase 1-style spike: de-risk a YouTube Music provider via ytmusic-api (NPM).
//
// Mirrors the Spotify spike (spotify_search.sh): prove the unknowns empirically
// before wiring anything into the app. Run:  node poc/ytmusic_search.mjs
//
// What this proves / probes:
//   1. SEARCH WITHOUT AUTH — ytmusic-api scrapes YT Music's internal API. Does
//      search work with NO cookies/login? (Spotify parallel: Client Credentials.)
//   2. NORMALIZATION — can a SongDetailed map cleanly onto our app's `Track`?
//   3. PLAYLIST GAP — the library is read-only (no createPlaylist). This script
//      documents that explicitly; see docs/youtube-music-poc.md for the verdict.
//
// IMPORTANT: ytmusic-api is a Node-only library (axios + cookie jar; it is NOT
// browser-safe). Like the Spotify integration, it must live behind our backend
// proxy — the app's YouTubeMusicProvider would call OUR API, never YT directly.

import { writeFile } from "node:fs/promises";
import YTMusic from "ytmusic-api";

const QUERIES = ["Radiohead", "Bohemian Rhapsody", "Daft Punk Discovery"];
const LIMIT = 10; // keep parity with the app's default search ceiling

// Map ytmusic-api's SongDetailed onto our normalized Track shape (src/music/types.ts).
// duration is in SECONDS here; the app uses ms. Picks the largest thumbnail for art.
function toTrack(song) {
  const art = [...(song.thumbnails ?? [])].sort((a, b) => b.width - a.width)[0];
  return {
    id: `youtube-music:${song.videoId}`,
    provider: "youtube-music",
    providerTrackId: song.videoId,
    title: song.name,
    artists: song.artist?.name ? [song.artist.name] : [],
    album: song.album?.name,
    artworkUrl: art?.url,
    durationMs: song.duration != null ? song.duration * 1000 : undefined,
    // ytmusic-api exposes no preview clip.
    externalUrl: `https://music.youtube.com/watch?v=${song.videoId}`,
  };
}

function fmt(ms) {
  if (!ms) return "—";
  const s = Math.round(ms / 1000);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
}

async function main() {
  const ytmusic = new YTMusic();
  // No cookies passed → fully unauthenticated. This is the key thing to prove.
  await ytmusic.initialize();
  console.log("✓ initialized ytmusic-api (no auth / no cookies)\n");

  const md = ["# YouTube Music PoC — search results", "", "_Generated by `poc/ytmusic_search.mjs` (ytmusic-api, unauthenticated)._", ""];

  for (const q of QUERIES) {
    console.log(`Search: "${q}"`);
    const songs = (await ytmusic.searchSongs(q)).slice(0, LIMIT);
    const tracks = songs.map(toTrack);

    for (const t of tracks) {
      console.log(`  • ${t.title} — ${t.artists.join(", ")}  [${fmt(t.durationMs)}]  ${t.providerTrackId}`);
    }
    console.log("");

    md.push(`## "${q}" — ${tracks.length} result(s)`, "");
    md.push("| Title | Artist | Album | Duration | videoId |", "|---|---|---|---|---|");
    for (const t of tracks) {
      md.push(`| ${t.title} | ${t.artists.join(", ")} | ${t.album ?? "—"} | ${fmt(t.durationMs)} | \`${t.providerTrackId}\` |`);
    }
    md.push("");
  }

  // Round-trip one track by id to prove getSong works too (the app's getTrack).
  const first = (await ytmusic.searchSongs(QUERIES[0]))[0];
  const full = await ytmusic.getSong(first.videoId);
  console.log(`✓ getSong("${first.videoId}") → "${full.name}"  (round-trip OK)`);

  await writeFile(new URL("../docs/SEARCH_RESULTS_YTMUSIC.md", import.meta.url), md.join("\n"));
  console.log("\n✓ wrote docs/SEARCH_RESULTS_YTMUSIC.md");
  console.log("\nNOTE: ytmusic-api is READ-ONLY — no createPlaylist. See docs/youtube-music-poc.md.");
}

main().catch((err) => {
  console.error("✗ PoC failed:", err?.message ?? err);
  process.exit(1);
});
